"""empty message

Revision ID: 4d9d0fb46fb6
Revises: None
Create Date: 2015-07-27 04:48:12.552000

"""

# revision identifiers, used by Alembic.
revision = '4d9d0fb46fb6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('firstname', sa.String(length=35), nullable=True),
    sa.Column('midname', sa.String(length=35), nullable=True),
    sa.Column('lastname', sa.String(length=35), nullable=True),
    sa.Column('datejoined', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('lastseen', sa.DateTime(), nullable=True),
    sa.Column('vk', sa.String(length=32), nullable=True),
    sa.Column('googleplus', sa.String(length=30), nullable=True),
    sa.Column('twitch', sa.String(length=30), nullable=True),
    sa.Column('tumblr', sa.String(length=35), nullable=True),
    sa.Column('spotify', sa.String(length=35), nullable=True),
    sa.Column('twitter', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=30), nullable=True),
    sa.Column('skype', sa.String(length=32), nullable=True),
    sa.Column('reddit', sa.String(length=20), nullable=True),
    sa.Column('linkedin', sa.String(length=10), nullable=True),
    sa.Column('github', sa.String(length=40), nullable=True),
    sa.Column('soundcloud', sa.String(length=255), nullable=True),
    sa.Column('steam', sa.String(length=20), nullable=True),
    sa.Column('pinterest', sa.String(length=15), nullable=True),
    sa.Column('alibaba', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('users')
    ### end Alembic commands ###
